I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 66, in script
    with moveinright((0.5, 1.0, 0.5, 1.0), dist=10)
  File "game/script.rpy", line 66, in <module>
    with moveinright((0.5, 1.0, 0.5, 1.0), dist=10)
TypeError: MoveTransition() got an unexpected keyword argument 'dist'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 66, in script
    with moveinright((0.5, 1.0, 0.5, 1.0), dist=10)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 1356, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Лена\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 66, in <module>
    with moveinright((0.5, 1.0, 0.5, 1.0), dist=10)
TypeError: MoveTransition() got an unexpected keyword argument 'dist'

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Zdybanka 1.0
Sat Jul 27 17:23:45 2024
